### ISSUE TITLE
Volunteer

### ISSUE THREAD

**Issue by liamja** [programmer-education-foundation/volunteers#3]
I'd be very happy to volunteer. I have a solid background in PHP and spend most of my time writing Ruby.

**Comment by xiongchiamiov** [comment]
Welcome, and thanks!

You can fork repositories to the organization, or keep them on your profile if you'd like.  Also, if you have any ideas for better explaining things to newbies, or useful code searches, feel free to add them to the website repo.

To-toro, to-to-ro :musical_note:
